steps:
  - id: install
    name: 'node:22'
    entrypoint: npm
    args: ['install']

  - id: lint
    name: 'node:22'
    entrypoint: npm
    args: ['run', 'pretest']
    waitFor: ['install']

  - id: test
    name: 'node:22'
    entrypoint: npm
    args: ['test']
    waitFor: ['install']

  - id: build
    name: 'node:22'
    entrypoint: npx
    args: ['tinyjam', 'example/', 'build/']
    waitFor: ['lint', 'test']

  - id: deploy
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-d', 'build/', 'gs://${_BUCKET_NAME}']
    waitFor: ['build']

substitutions:
  _BUCKET_NAME: 'tinyjam-static-site-sdlc-test'

options:
  logging: CLOUD_LOGGING_ONLY
